language: python

python:
    - 2.7

services: 
    - mysql

env:
    global:
        - DJANGO_SETTINGS_MODULE=invisum.settings
        - PYTHONPATH=$HOME/builds/LionsWrath/invisum-api
        - PIP_USE_MIRRORS=true
        - SECRET_KEY='f(mm#q1k*^vk@v_hg9um6zo)9u7#pztgr8!yeq(+#*&wglwei_'

install:
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    
    # Useful for debugging any issues with conda
    - conda info -a

    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION anaconda
    - source activate test-environment

    - pip install -r requirements.txt
    - pip install -q mysql-python

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres

script:
    - python manage.py makemigrations datasets
    - python manage.py migrate 
    - python manage.py test

notifications:
    email:
        on_success: change
        on_failure: always
